### ISSUE TITLE
What's the plan regarding UrqlCombinedError.t?

### ISSUE THREAD

**Issue by gugahoa** [FormidableLabs/reason-urql#87] opened 2019-07-06 19:35 UTC
Hello, all!
I have been using `reason-urql` since hooks got in, and one of the pain points has been around error handling. Right now, there's no way to inspect the errors that happened during a request, as the error type is simply an `UrqlCombinedError.t` with no helper function to extract more information from that type.

What's the plan regarding error handling, and is this error API what's gonna ship with 1.0?

**Comment by parkerziegler** [comment] 2019-07-06 20:56
@gugahoa the `UrqlCombinedError` API is definitely rough (I actually think it's just broken right now). I think I see where the issue is – there's a binding to support `new`ing up a `CombinedError`, but users are never actually doing that, they're just receiving a `CombinedError` instance from `urql`. I'll work on a prototype this afternoon, but the short answer is no, we'll fix this API before shipping a formal `v1`. The beta I mentioned will still go out with it so folks can use the hooks now ✅, and I'll probably release another beta when this API gets fixed. I just don't want to release a `v1` and then need to start doing lots of semver releases that disrupt folks.

**Comment by parkerziegler** [comment] 2019-07-22 16:27
Closed by #89.

**Closed by parkerziegler** 2019-07-22 16:27 UTC

**Comment by parkerziegler** [comment] 2019-07-23 00:38
Released in v1.0.0-beta.2.
